export type DailyTask = {
  id: string;
  title: string;
  description: string;
  category: "Kubernetes" | "AWS" | "Azure" | "CI/CD" | "IaC" | "Docker" | "Linux";
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  estMinutes: number;
};

export const dailyTasks: DailyTask[] = [
  {
    id: "t1",
    title: "Write a multi-stage Dockerfile",
    description: "Containerize a simple Node.js or Python app using a multi-stage build to keep the final image small.",
    category: "Docker",
    difficulty: "Beginner",
    estMinutes: 20,
  },
  {
    id: "t2",
    title: "Set up a GitHub Actions CI workflow",
    description: "Create a workflow that runs on every push: install dependencies, lint, and run tests.",
    category: "CI/CD",
    difficulty: "Beginner",
    estMinutes: 25,
  },
  {
    id: "t3",
    title: "Provision an S3 bucket with Terraform",
    description: "Write a Terraform config that creates a versioned, private S3 bucket with a lifecycle rule.",
    category: "IaC",
    difficulty: "Intermediate",
    estMinutes: 30,
  },
  {
    id: "t4",
    title: "Deploy an app to a local Kubernetes cluster",
    description: "Use kind or minikube to spin up a cluster and deploy a sample app with a Deployment + Service.",
    category: "Kubernetes",
    difficulty: "Intermediate",
    estMinutes: 35,
  },
  {
    id: "t5",
    title: "Write a log rotation script",
    description: "Write a bash script that deletes or archives log files older than 7 days in a given directory.",
    category: "Linux",
    difficulty: "Beginner",
    estMinutes: 15,
  },
  {
    id: "t6",
    title: "Configure a Kubernetes readiness probe",
    description: "Add a readiness probe to an existing Deployment so traffic only routes to pods once they're actually ready.",
    category: "Kubernetes",
    difficulty: "Intermediate",
    estMinutes: 20,
  },
  {
    id: "t7",
    title: "Set up an AWS IAM role with least privilege",
    description: "Create an IAM role and policy that grants only the specific S3 and CloudWatch permissions a service needs.",
    category: "AWS",
    difficulty: "Intermediate",
    estMinutes: 25,
  },
  {
    id: "t8",
    title: "Build a CI/CD pipeline with a manual approval gate",
    description: "Add a manual approval step before the production deploy stage in your pipeline of choice.",
    category: "CI/CD",
    difficulty: "Advanced",
    estMinutes: 30,
  },
  {
    id: "t9",
    title: "Write a Terraform module",
    description: "Refactor a Terraform config into a reusable module that accepts variables for environment name and instance size.",
    category: "IaC",
    difficulty: "Advanced",
    estMinutes: 40,
  },
  {
    id: "t10",
    title: "Deploy a container to Azure Container Apps",
    description: "Push a container image to Azure Container Registry and deploy it using Azure Container Apps.",
    category: "Azure",
    difficulty: "Intermediate",
    estMinutes: 30,
  },
  {
    id: "t11",
    title: "Set resource requests and limits",
    description: "Add CPU/memory requests and limits to a Kubernetes Deployment and observe how the scheduler responds.",
    category: "Kubernetes",
    difficulty: "Intermediate",
    estMinutes: 20,
  },
  {
    id: "t12",
    title: "Write a docker-compose stack",
    description: "Define a docker-compose.yml that runs an app, a database, and a reverse proxy together.",
    category: "Docker",
    difficulty: "Beginner",
    estMinutes: 25,
  },
  {
    id: "t13",
    title: "Create a GitHub Actions matrix build",
    description: "Configure a workflow that tests against multiple Node/Python versions in parallel using a build matrix.",
    category: "CI/CD",
    difficulty: "Advanced",
    estMinutes: 25,
  },
  {
    id: "t14",
    title: "Set up remote Terraform state",
    description: "Move a local Terraform state file to a remote backend (S3 + DynamoDB lock, or Terraform Cloud).",
    category: "IaC",
    difficulty: "Advanced",
    estMinutes: 30,
  },
  {
    id: "t15",
    title: "Write a systemd service file",
    description: "Package a small app as a systemd service that starts on boot and restarts automatically on failure.",
    category: "Linux",
    difficulty: "Intermediate",
    estMinutes: 20,
  },
  {
    id: "t16",
    title: "Configure Kubernetes horizontal pod autoscaling",
    description: "Set up an HPA that scales a Deployment based on CPU utilization.",
    category: "Kubernetes",
    difficulty: "Advanced",
    estMinutes: 30,
  },
  {
    id: "t17",
    title: "Set up AWS CloudWatch alarms",
    description: "Create a CloudWatch alarm that notifies you (via SNS) when CPU utilization exceeds a threshold.",
    category: "AWS",
    difficulty: "Intermediate",
    estMinutes: 25,
  },
  {
    id: "t18",
    title: "Write an Azure Resource Manager (ARM) or Bicep template",
    description: "Define a storage account and resource group using an ARM/Bicep template instead of the portal.",
    category: "Azure",
    difficulty: "Advanced",
    estMinutes: 35,
  },
  {
    id: "t19",
    title: "Add a pre-commit hook",
    description: "Set up a Git pre-commit hook that runs a linter or formatter before every commit.",
    category: "CI/CD",
    difficulty: "Beginner",
    estMinutes: 15,
  },
  {
    id: "t20",
    title: "Practice a blue-green deployment",
    description: "Simulate a blue-green deployment locally: run two versions side by side and switch traffic between them.",
    category: "CI/CD",
    difficulty: "Advanced",
    estMinutes: 35,
  },
];
