export type Snippet = {
  id: string;
  title: string;
  language: string;
  lines: string[];
  buggyLine: number; // 0-indexed
  explanation: string;
};

export const debugSnippets: Snippet[] = [
  {
    id: "k8s-deployment",
    title: "Kubernetes Deployment",
    language: "yaml",
    lines: [
      "apiVersion: apps/v1",
      "kind: Deployment",
      "metadata:",
      "  name: resume-ai",
      "spec:",
      "  replica: 3",
      "  selector:",
      "    matchLabels:",
      "      app: resume-ai",
    ],
    buggyLine: 5,
    explanation: "The field is 'replicas' (plural), not 'replica'. As written, Kubernetes will reject this or silently default to 1 replica.",
  },
  {
    id: "dockerfile-base",
    title: "Dockerfile",
    language: "dockerfile",
    lines: [
      "FROM node:20-alpine",
      "WORKDIR /app",
      "COPY package*.json ./",
      "RUN npm install",
      "COPY . .",
      "EXPOSE 5000",
      "CMD [\"node\", \"server.js\"]",
      "# app listens on process.env.PORT || 8080",
    ],
    buggyLine: 5,
    explanation: "EXPOSE 5000 doesn't match the port the app actually listens on (8080, per the comment). Anyone mapping -p 5000:5000 will get connection refused.",
  },
  {
    id: "github-actions",
    title: "GitHub Actions Workflow",
    language: "yaml",
    lines: [
      "name: Deploy",
      "on: push",
      "jobs:",
      "  deploy:",
      "    runs-on: ubuntu-latest",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - name: Deploy to server",
      "        env:",
      "          API_KEY: ${{ secret.API_KEY }}",
      "        run: ./deploy.sh",
    ],
    buggyLine: 9,
    explanation: "It's 'secrets.API_KEY' (plural), not 'secret.API_KEY'. The typo means the environment variable resolves to empty at runtime.",
  },
  {
    id: "docker-compose",
    title: "Docker Compose",
    language: "yaml",
    lines: [
      "services:",
      "  api:",
      "    image: akops/api:1.4.0",
      "    depends_on:",
      "      - dataabse",
      "  database:",
      "    image: postgres:16",
      "    ports:",
      "      - \"5432:5432\"",
    ],
    buggyLine: 4,
    explanation: "'dataabse' is a typo — the actual service is named 'database'. Compose will fail to resolve the dependency.",
  },
  {
    id: "nginx-conf",
    title: "Nginx Config",
    language: "nginx",
    lines: [
      "server {",
      "  listen 80;",
      "  server_name akopslabs.com;",
      "",
      "  location / {",
      "    proxy_pass http://localhost:3000",
      "    proxy_set_header Host $host;",
      "  }",
      "}",
    ],
    buggyLine: 5,
    explanation: "Missing semicolon at the end of 'proxy_pass http://localhost:3000'. Nginx directives must end with ';' or the config fails to reload.",
  },
  {
    id: "terraform-instance",
    title: "Terraform Resource",
    language: "hcl",
    lines: [
      "resource \"aws_instance\" \"web\" {",
      "  ami           = \"ami-0c9\"",
      "  instance_type = \"t3.micro\"",
      "  tags = {",
      "    Name = \"akops-web\"",
      "  }",
      "}",
    ],
    buggyLine: 1,
    explanation: "\"ami-0c9\" is not a valid AMI ID — real AMI IDs are much longer (e.g. ami-0c94855ba95c71c99). This would fail at apply time.",
  },
  {
    id: "dockerfile-cache",
    title: "Dockerfile Layer Order",
    language: "dockerfile",
    lines: [
      "FROM python:3.12-slim",
      "WORKDIR /app",
      "COPY . .",
      "RUN pip install -r requirements.txt",
      "CMD [\"python\", \"app.py\"]",
    ],
    buggyLine: 2,
    explanation: "Copying all source before installing dependencies busts the Docker layer cache on every code change. requirements.txt should be copied and installed first, then the rest of the source.",
  },
  {
    id: "k8s-probe",
    title: "Kubernetes Liveness Probe",
    language: "yaml",
    lines: [
      "containers:",
      "  - name: api",
      "    image: akops/api:2.1.0",
      "    ports:",
      "      - containerPort: 8080",
      "    livenessProbe:",
      "      httpGet:",
      "        path: /healthz",
      "        port: 8081",
    ],
    buggyLine: 8,
    explanation: "The liveness probe checks port 8081, but the container only exposes port 8080. The probe will always fail and Kubernetes will keep restarting the pod.",
  },
];
