export type Question = {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  category: string;
};

export const triviaQuestions: Question[] = [
  {
    id: "q1",
    question: "Which command builds a Docker image from a Dockerfile in the current directory?",
    options: ["docker run .", "docker build .", "docker create .", "docker compose ."],
    correctIndex: 1,
    category: "Docker",
  },
  {
    id: "q2",
    question: "In Kubernetes, what is the smallest deployable unit?",
    options: ["Container", "Node", "Pod", "Deployment"],
    correctIndex: 2,
    category: "Kubernetes",
  },
  {
    id: "q3",
    question: "What does CI stand for in CI/CD?",
    options: ["Code Integration", "Continuous Integration", "Container Instance", "Continuous Inspection"],
    correctIndex: 1,
    category: "CI/CD",
  },
  {
    id: "q4",
    question: "Which AWS service is primarily used for object storage?",
    options: ["EC2", "RDS", "S3", "Lambda"],
    correctIndex: 2,
    category: "Cloud",
  },
  {
    id: "q5",
    question: "What Git command creates a new branch and switches to it in one step?",
    options: ["git branch -m", "git checkout -b", "git switch --new", "git merge -b"],
    correctIndex: 1,
    category: "Git",
  },
  {
    id: "q6",
    question: "In Kubernetes, which object manages a set of replica Pods and ensures a stable set is always running?",
    options: ["Service", "ConfigMap", "Deployment", "Ingress"],
    correctIndex: 2,
    category: "Kubernetes",
  },
  {
    id: "q7",
    question: "What is the primary purpose of Terraform?",
    options: [
      "Container orchestration",
      "Infrastructure as Code provisioning",
      "Log aggregation",
      "Continuous deployment only",
    ],
    correctIndex: 1,
    category: "IaC",
  },
  {
    id: "q8",
    question: "Which HTTP status code indicates a successful request?",
    options: ["404", "500", "200", "301"],
    correctIndex: 2,
    category: "Fundamentals",
  },
  {
    id: "q9",
    question: "What does 'idempotent' mean in the context of infrastructure automation?",
    options: [
      "It can only run once",
      "Running it multiple times produces the same result as running it once",
      "It requires manual approval",
      "It automatically rolls back on failure",
    ],
    correctIndex: 1,
    category: "Fundamentals",
  },
  {
    id: "q10",
    question: "Which Kubernetes object exposes a set of Pods as a network service?",
    options: ["Service", "Namespace", "Volume", "Secret"],
    correctIndex: 0,
    category: "Kubernetes",
  },
  {
    id: "q11",
    question: "In FinOps, what does 'rightsizing' refer to?",
    options: [
      "Resizing container images",
      "Matching cloud resource capacity to actual workload needs to reduce cost",
      "Increasing instance count automatically",
      "Compressing log files",
    ],
    correctIndex: 1,
    category: "FinOps",
  },
  {
    id: "q12",
    question: "What is the default port that a Docker container's web server commonly needs mapped with '-p' to be reachable from the host?",
    options: ["It's automatic, no mapping needed", "22", "You must explicitly map host:container ports", "443 always"],
    correctIndex: 2,
    category: "Docker",
  },
  {
    id: "q13",
    question: "Which of these is a canary deployment strategy?",
    options: [
      "Deploying to 100% of users immediately",
      "Gradually rolling out a change to a small subset of users before full release",
      "Deploying only on weekends",
      "Rolling back automatically after every deploy",
    ],
    correctIndex: 1,
    category: "CI/CD",
  },
  {
    id: "q14",
    question: "What does 'IAM' stand for in cloud platforms?",
    options: ["Internal Access Monitor", "Identity and Access Management", "Infrastructure Automation Module", "Integrated Application Manager"],
    correctIndex: 1,
    category: "Cloud",
  },
  {
    id: "q15",
    question: "Which command shows the commit history in Git?",
    options: ["git status", "git log", "git diff", "git show-history"],
    correctIndex: 1,
    category: "Git",
  },
  {
    id: "q16",
    question: "In AIOps, what is 'anomaly detection' primarily used for?",
    options: [
      "Writing documentation automatically",
      "Identifying unusual patterns in metrics/logs that may indicate an incident",
      "Compiling source code faster",
      "Managing user permissions",
    ],
    correctIndex: 1,
    category: "AIOps",
  },
  {
    id: "q17",
    question: "What is a 'blue-green deployment'?",
    options: [
      "A deployment that only runs at night",
      "Running two identical production environments and switching traffic between them",
      "A deployment strategy using only two servers total",
      "Color-coding logs by severity",
    ],
    correctIndex: 1,
    category: "CI/CD",
  },
  {
    id: "q18",
    question: "Which file format does Kubernetes typically use for defining manifests?",
    options: ["XML", "YAML", "INI", "CSV"],
    correctIndex: 1,
    category: "Kubernetes",
  },
];

export const moreTriviaQuestions: Question[] = [
  // Kubernetes
  {
    id: "k8s1",
    question: "Which Kubernetes object stores non-confidential configuration data as key-value pairs?",
    options: ["Secret", "ConfigMap", "PersistentVolume", "DaemonSet"],
    correctIndex: 1,
    category: "Kubernetes",
  },
  {
    id: "k8s2",
    question: "What does 'kubectl get pods -n <namespace>' do?",
    options: [
      "Deletes all pods in a namespace",
      "Lists pods running in a specific namespace",
      "Creates a new namespace",
      "Scales a deployment",
    ],
    correctIndex: 1,
    category: "Kubernetes",
  },
  {
    id: "k8s3",
    question: "Which controller runs exactly one copy of a Pod on every (or selected) node?",
    options: ["ReplicaSet", "DaemonSet", "StatefulSet", "Job"],
    correctIndex: 1,
    category: "Kubernetes",
  },
  {
    id: "k8s4",
    question: "What is a Kubernetes 'Ingress' primarily used for?",
    options: [
      "Storing secrets",
      "Routing external HTTP/HTTPS traffic to services inside the cluster",
      "Scheduling pods to nodes",
      "Managing container images",
    ],
    correctIndex: 1,
    category: "Kubernetes",
  },
  {
    id: "k8s5",
    question: "Which Kubernetes workload type is best suited for stateful applications like databases?",
    options: ["Deployment", "StatefulSet", "ReplicaSet", "Job"],
    correctIndex: 1,
    category: "Kubernetes",
  },
  // AWS
  {
    id: "aws1",
    question: "Which AWS service provides managed relational databases?",
    options: ["S3", "RDS", "Lambda", "CloudFront"],
    correctIndex: 1,
    category: "AWS",
  },
  {
    id: "aws2",
    question: "Which AWS service lets you run code without provisioning or managing servers?",
    options: ["EC2", "Lambda", "ECS", "Lightsail"],
    correctIndex: 1,
    category: "AWS",
  },
  {
    id: "aws3",
    question: "Which AWS service is a global content delivery network (CDN)?",
    options: ["Route 53", "CloudFront", "VPC", "SNS"],
    correctIndex: 1,
    category: "AWS",
  },
  {
    id: "aws4",
    question: "What does AWS IAM primarily manage?",
    options: ["Network bandwidth", "Users, roles, and permissions", "Database backups", "DNS records"],
    correctIndex: 1,
    category: "AWS",
  },
  {
    id: "aws5",
    question: "Which AWS service is used for scalable DNS management?",
    options: ["Route 53", "CloudWatch", "IAM", "S3"],
    correctIndex: 0,
    category: "AWS",
  },
  {
    id: "aws6",
    question: "Which S3 storage class is designed for rarely accessed, long-term archival data at the lowest cost?",
    options: ["S3 Standard", "S3 Intelligent-Tiering", "S3 Glacier Deep Archive", "S3 One Zone-IA"],
    correctIndex: 2,
    category: "AWS",
  },
  // Azure
  {
    id: "az1",
    question: "What is the Azure equivalent of AWS EC2 (virtual servers)?",
    options: ["Azure Functions", "Azure Virtual Machines", "Azure Blob Storage", "Azure Monitor"],
    correctIndex: 1,
    category: "Azure",
  },
  {
    id: "az2",
    question: "Which Azure service provides managed Kubernetes clusters?",
    options: ["AKS (Azure Kubernetes Service)", "ACR", "AVM", "AFD"],
    correctIndex: 0,
    category: "Azure",
  },
  {
    id: "az3",
    question: "What is an Azure Resource Group used for?",
    options: [
      "A billing discount tier",
      "A logical container for grouping related Azure resources",
      "A type of virtual machine",
      "A network firewall rule",
    ],
    correctIndex: 1,
    category: "Azure",
  },
  {
    id: "az4",
    question: "Which Azure service offers serverless, event-driven compute?",
    options: ["Azure Functions", "Azure Virtual Machines", "Azure Blob Storage", "Azure DevOps"],
    correctIndex: 0,
    category: "Azure",
  },
  {
    id: "az5",
    question: "What does Azure Active Directory (Microsoft Entra ID) primarily manage?",
    options: ["Storage replication", "Identity and access management", "Load balancing", "Container registries"],
    correctIndex: 1,
    category: "Azure",
  },
  {
    id: "az6",
    question: "Which Azure service is used to build and run CI/CD pipelines?",
    options: ["Azure Pipelines (Azure DevOps)", "Azure Blob Storage", "Azure Monitor", "Azure Key Vault"],
    correctIndex: 0,
    category: "Azure",
  },
  // CI/CD
  {
    id: "cicd1",
    question: "What is a 'build artifact' in a CI/CD pipeline?",
    options: [
      "A test report only",
      "The packaged output of a build step (e.g. a binary, container image, or archive)",
      "A Git commit message",
      "A deployment schedule",
    ],
    correctIndex: 1,
    category: "CI/CD",
  },
  {
    id: "cicd2",
    question: "What does 'GitOps' mean?",
    options: [
      "Storing secrets in Git",
      "Using Git as the single source of truth to drive automated deployments",
      "A branching strategy for solo developers",
      "Deleting old Git branches automatically",
    ],
    correctIndex: 1,
    category: "CI/CD",
  },
  {
    id: "cicd3",
    question: "In a pipeline, what does 'rollback' mean?",
    options: [
      "Reverting to a previously known-good deployment after a failed release",
      "Rewriting Git history",
      "Restarting the build server",
      "Merging a feature branch",
    ],
    correctIndex: 0,
    category: "CI/CD",
  },
  {
    id: "cicd4",
    question: "Why do CI pipelines cache dependencies (e.g. node_modules) between runs?",
    options: [
      "It's required by Git",
      "To speed up builds by avoiding redundant downloads/installs",
      "To pass compliance audits",
      "It has no effect on speed",
    ],
    correctIndex: 1,
    category: "CI/CD",
  },
  {
    id: "cicd5",
    question: "What does 'shift-left testing' mean in a CI/CD context?",
    options: [
      "Running tests only in production",
      "Moving testing earlier in the development process, closer to when code is written",
      "Testing only the UI",
      "Skipping tests to ship faster",
    ],
    correctIndex: 1,
    category: "CI/CD",
  },
  // IaC
  {
    id: "iac1",
    question: "What is 'drift' in Infrastructure as Code?",
    options: [
      "A Terraform syntax error",
      "When real-world infrastructure no longer matches what's defined in code",
      "A type of cloud region failover",
      "The time it takes to run 'terraform apply'",
    ],
    correctIndex: 1,
    category: "IaC",
  },
  {
    id: "iac2",
    question: "What does a Terraform 'state file' track?",
    options: [
      "Application logs",
      "The current mapping between your configuration and real infrastructure resources",
      "User login sessions",
      "Container image layers",
    ],
    correctIndex: 1,
    category: "IaC",
  },
  {
    id: "iac3",
    question: "What's the difference between 'terraform plan' and 'terraform apply'?",
    options: [
      "There is no difference",
      "'plan' previews changes; 'apply' actually makes them",
      "'plan' deletes resources; 'apply' creates them",
      "'apply' only works locally",
    ],
    correctIndex: 1,
    category: "IaC",
  },
  {
    id: "iac4",
    question: "What is a Terraform 'module' used for?",
    options: [
      "Encrypting state files",
      "Packaging reusable, configurable groups of resources",
      "Running unit tests",
      "Managing IAM users only",
    ],
    correctIndex: 1,
    category: "IaC",
  },
  {
    id: "iac5",
    question: "Which of these is a core benefit of Infrastructure as Code?",
    options: [
      "Infrastructure changes are undocumented and manual",
      "Infrastructure becomes version-controlled, repeatable, and reviewable like application code",
      "It eliminates the need for testing",
      "It only works with a single cloud provider",
    ],
    correctIndex: 1,
    category: "IaC",
  },
  {
    id: "iac6",
    question: "What does 'terraform destroy' do?",
    options: [
      "Deletes the Terraform binary",
      "Tears down all resources managed by that Terraform configuration",
      "Resets the state file only",
      "Formats .tf files",
    ],
    correctIndex: 1,
    category: "IaC",
  },
];

export const allTriviaQuestions: Question[] = [...triviaQuestions, ...moreTriviaQuestions];
